apiVersion: apps/v1
kind: Deployment
metadata:
    name: docker-k8s-deployment
    labels:
        app: docker-k8s
spec:
    replicas: 1
    selector:
        matchLabels:
            app: docker-k8s
    template:
        metadata:
            labels:
                app: docker-k8s
        spec:
            containers:
            - name: docker-k8s
              image: it19110530/assignment3:a673321787f6f24152d1e4254f4219ba81377642
              ports:
              - containerPort: 8030