apiVersion: apps/v1
kind: Service
metadata:
    name: docker-k8s-deployment
spec:
    selector:
      app: docker-k8s
    type: LoadBalancer
    ports:
      - port: 80
        targetPort: 8030
 
      